package com.tschool.railwayapp.commons.commands;

public enum Command { 
    CREATE_PATH,
    CREATE_STATION,
    CREATE_TICKET,
    CREATE_TIMETABLE,
    CREATE_TRAIN,
    CREATE_USER,
    GET_PATHS_FIT_STATIONS,
    GET_TIMETABLES_FIT_PATHS_DATE,
    GET_TRAIN_TYPE_LIST,
    GET_TRAIN_AND_PATH_LIST,
    GET_STATION_LIST,
    IS_SIGNED_UP
}
